Device found
Total features gathered 1408034, problem size: 1408034
Traceback (most recent call last):
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/generate_proxy_training_labels.py", line 49, in <module>
    main(None)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/generate_proxy_training_labels.py", line 46, in main
    energy = k_means.train(cached_features=feature_bank)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/src/k_means.py", line 59, in train
    print(f"Training K-means with {x.shape[0]} vectors of dimension {x.shape[1]}")
IndexError: tuple index out of range
